### PR TITLE
chore: prepare for laravel 11

### PR DESCRIPTION
**Pull request by joostdebruijn**
Prepares for the release of Laravel 11 within a few weeks.

### CODE REVIEW

**Comment by joostdebruijn** [comment]
@danielme85 It's now running well with Laravel 10, however for Laravel 11 the dependency `mongodb/laravel-mongodb` should be updated to work with Laravel 11. Will have a look at that later.

**Comment by danielme85** [comment]
> @danielme85 It's now running well with Laravel 10, however for Laravel 11 the dependency `mongodb/laravel-mongodb` should be updated to work with Laravel 11. Will have a look at that later.

thanks @joostdebruijn 👍 , we might just have to wait for laravel-mongodb to update their package requirements.

**Comment by danielme85** [comment]
I think I'll separate out all mongodb testing and skip them for L11 then make an alpha release or something ¯\_(ツ)_/¯ 

Silly to be held back if you don't use mongodb at all.

**Comment by danielme85** [comment]
Aright all good, thanks!

**Pull request merged**
